
networks:
  keycloak:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  keycloak_postgres_data:
    driver: local

services:
  postgres:
    container_name: control-booth-postgresql
    image: postgres:18.1
    environment:
    - POSTGRES_DB=control-booth
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - 5433:5432
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data

  keycloak_postgresql:
    container_name: control-booth-keycloak-postgresql
    image: postgres:16.8
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: "exit 0"
    #ports:
    #  - 5434:5432
    networks:
      - keycloak
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak:
    container_name: control-booth-keycloak
    image: quay.io/keycloak/keycloak
    command: start-dev
    healthcheck:
      test: "exit 0"
    environment:
      KC_DB: postgres
      #KC_DB_URL_HOST: keycloak_postgresql
      KC_DB_URL_HOST: control-booth-keycloak-postgresql
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: 123456
      KC_DB_SCHEMA: public
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 9000:8080
    depends_on:
      keycloak_postgresql:
        condition: service_healthy
    networks:
      - keycloak

  keycloak-config-cli:
    container_name: control-booth-keycloak-cli
    image: adorsys/keycloak-config-cli:latest
    environment:
      #KEYCLOAK_URL: "http://keycloak:8080/"
      KEYCLOAK_URL: "http://control-booth-keycloak:8080/"
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: true
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: 120s
      IMPORT_FILES_LOCATIONS: "/config/*"
    volumes:
      - ./keycloak-config:/config
    depends_on:
      - keycloak
      - openldap
    networks:
      - keycloak
      
  openldap:
    container_name: control-booth-openldap
    #image: cleanstart/openldap:latest
    #image: stagex/openldap:2.6.8
    image: osixia/openldap:latest
    environment:
      LDAP_BASE_DN: "dc=control-booth,dc=org"
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "control-booth.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"             # deactivate TLS for the LDAP server
    volumes:
      - ./ldap/gcp-ldap-sample.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    networks:
      - keycloak
    ports:
      - "389:389"                   # default port for unsecured LDAP
    command: --copy-service
    restart: unless-stopped

  phpldapadmin:
    container_name: control-booth-phpldapadmin
    image: osixia/phpldapadmin:0.9.0
    environment:
      #PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_LDAP_HOSTS: control-booth-openldap
      PHPLDAPADMIN_HTTPS: "false"   # deactivate HTTPS
    networks:
      - keycloak
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - openldap
